import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { Header } from "./components/Header"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Fondo con gradiente - FIXED y z-0 */}
        <div className="fixed inset-0 bg-gradient-to-br from-[#233329] via-[#0a0a0a] to-[#0a0a0a] -z-10"></div>

        {/* Glowing orbs - FIXED y z-0 */}
        <div className="fixed top-20 left-20 w-96 h-96 bg-[#63d471] rounded-full blur-[120px] opacity-20 animate-pulse -z-10"></div>
        <div
          className="fixed bottom-20 right-20 w-96 h-96 bg-[#69fff1] rounded-full blur-[120px] opacity-15 animate-pulse -z-10"
          style={{ animationDelay: "1s" }}
        ></div>

        {/* Contenido principal */}
        <Header />
        <div className="relative z-10 text-white">{children}</div>
      </body>
    </html>
  )
}
